# This is a basic workflow that is manually triggered

name: Scan and import package

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Package name'
        default: 'requests'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Package version'
        default: '2.3.1'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Download package
      run: echo "Downloading package ${{ inputs.name }}${{ inputs.version }}"
    - name: Download File
      run: |
        set -euo pipefail

        url=$(curl -sS "https://pypi.org/pypi/requests/2.31.0/json" \
          | jq -r '.urls[] | select(.packagetype == "sdist") | .url')

        echo "Downloading: $url"
        curl -L "$url" --output ./file.tar.gz
      working-directory: ${{ github.workspace }}
    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
          input: ${{ github.workspace }}/file.tar.gz
          format: "table"
          scan-type: "fs"
          exit-code: 1
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
      

